#!/usr/bin/env node
// vim:ft=javascript:ts=2:sw=2:et:
'use strict';

const argv = process.argv.slice(2);
const options = argv.filter(v => v.startsWith('--'));

const sourceFiles = argv.filter(v => !options.includes(v));
if (sourceFiles.length === 0) {
  console.warn('No args');
  process.exit(1);
}

const ANSI = require('ansi-string');
const {tagJavaScriptFile} = require('.');
const {printTag} = require('./common.js');

sourceFiles.forEach(async f => {
  try {
    (await tagJavaScriptFile(f)).forEach(printTag);
  } catch(e) {
    if (!(e instanceof TypeError)) throw e;
    console.warn(ANSI.red`[WARNING] ${f} is not a valid javascript or empty.`);
  }
});
